services:
  redis1:
    image: redis:8
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    mem_limit: 1g
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"